# Generated by Django 3.0.3 on 2020-05-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='event',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Engine.Event'),
        ),
    ]
