# Generated by Django 3.0.3 on 2020-05-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0002_response_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='responses',
            field=models.ManyToManyField(blank=True, to='Engine.Response'),
        ),
    ]
