# Generated by Django 3.0.3 on 2020-05-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0003_gamedata_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedata',
            name='skipval',
            field=models.IntegerField(default=0),
        ),
    ]
