# Generated by Django 3.0.3 on 2020-05-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0004_savedata_skipval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedata',
            name='skipval',
        ),
        migrations.AddField(
            model_name='savedata',
            name='alreadyasked',
            field=models.ManyToManyField(blank=True, to='Engine.Event'),
        ),
    ]
