# Generated by Django 3.0.3 on 2020-05-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0005_auto_20200503_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedata',
            name='alreadyasked',
            field=models.ManyToManyField(blank=True, default='', to='Engine.Event'),
        ),
    ]
