# Generated by Django 3.0.3 on 2020-05-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0006_auto_20200503_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='Disqualifier',
            field=models.ManyToManyField(blank=True, related_name='Noes', to='Engine.Response'),
        ),
        migrations.AddField(
            model_name='response',
            name='ReqEvents',
            field=models.ManyToManyField(blank=True, related_name='Prereq', to='Engine.Response'),
        ),
        migrations.AddField(
            model_name='response',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
