# Generated by Django 3.0.3 on 2020-05-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0007_auto_20200503_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='hidden_when_inactive',
            field=models.BooleanField(default=True),
        ),
    ]
