# Generated by Django 3.0.3 on 2020-05-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0009_auto_20200503_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hidden_when_inactive',
        ),
    ]
