# Generated by Django 3.0.3 on 2020-05-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0011_routes_hidden_when_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='activeresponse',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
