# Generated by Django 3.0.3 on 2020-05-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0012_response_activeresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='openpath',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
