# Generated by Django 3.0.3 on 2020-05-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0013_auto_20200503_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='activate_on_entry',
            field=models.ManyToManyField(blank=True, related_name='visitactive', to='Engine.Room'),
        ),
        migrations.AddField(
            model_name='response',
            name='auto_activate',
            field=models.ManyToManyField(blank=True, related_name='autoactive', to='Engine.Response'),
        ),
        migrations.AddField(
            model_name='savedata',
            name='visited',
            field=models.ManyToManyField(blank=True, default='', related_name='visits', to='Engine.Room'),
        ),
    ]
