# Generated by Django 3.0.3 on 2020-05-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0014_auto_20200503_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('winstate', models.BooleanField(blank=True, default=True)),
                ('responses', models.ManyToManyField(blank=True, to='Engine.Response')),
                ('rooms', models.ManyToManyField(blank=True, to='Engine.Room')),
            ],
        ),
        migrations.AddField(
            model_name='gamedata',
            name='objectives',
            field=models.ManyToManyField(blank=True, to='Engine.ObjectiveState'),
        ),
    ]
