# Generated by Django 3.0.3 on 2020-05-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0015_auto_20200503_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectivestate',
            name='room_and_response_condition',
            field=models.BooleanField(default=False),
        ),
    ]
