# Generated by Django 3.0.3 on 2020-05-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0016_objectivestate_room_and_response_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
