# Generated by Django 3.0.3 on 2020-05-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0017_routes_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_responses',
            field=models.ManyToManyField(blank=True, related_name='AutoResponses', to='Engine.Response'),
        ),
    ]
