# Generated by Django 3.0.3 on 2020-05-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0018_event_auto_responses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
