# Generated by Django 3.0.3 on 2020-05-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0019_delete_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomvalue',
        ),
    ]
