# Generated by Django 3.0.3 on 2020-05-04 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0020_remove_room_roomvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='gamelikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='userlikes', to='Engine.GameData'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=1000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentgame', to='Engine.GameData')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gamedata',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='gamecomments', to='Engine.Comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='usercomments', to='Engine.Comment'),
        ),
    ]
