# Generated by Django 3.0.3 on 2020-05-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0021_auto_20200504_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
