# Generated by Django 3.0.3 on 2020-05-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0022_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='disqualifier',
            field=models.ManyToManyField(blank=True, default='', related_name='disqual', to='Engine.Response'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='reqresponse',
            field=models.ManyToManyField(blank=True, default='', related_name='requirements', to='Engine.Response'),
        ),
    ]
